/*
 * 数据文件：包含不同场景下的学习短语和单词。
 * 该文件由多个数组组成，每个数组包含对象，描述英文表达、中文翻译以及使用场景。
 */


/*
 * 为避免在最终网站上出现调试信息，已删除调试相关代码。
 * data.js 仅负责定义数据数组和将其挂载到 window 对象，供主脚本调用。
 */

// 幼儿园英语（Childcare English）
const childcareData = [
  // 早晨送园
  { id: 'cc-1', english: 'Good morning!', chinese: '早上好！', scenario: '早晨送园' },
  { id: 'cc-2', english: 'Did she have breakfast?', chinese: '她吃早饭了吗？', scenario: '早晨送园' },
  { id: 'cc-3', english: 'Any special instructions for today?', chinese: '今天有什么特别需要注意的吗？', scenario: '早晨送园' },
  { id: 'cc-4', english: 'Is she bringing her lunch?', chinese: '她带午饭了吗？', scenario: '早晨送园' },
  { id: 'cc-5', english: 'Please sign her in.', chinese: '请帮她签到。', scenario: '早晨送园' },
  { id: 'cc-6', english: 'She\'s a bit shy today.', chinese: '她今天有点害羞。', scenario: '早晨送园' },
  { id: 'cc-7', english: 'Let me know if she needs anything.', chinese: '如果她需要任何帮助，请告诉我。', scenario: '早晨送园' },
  { id: 'cc-8', english: 'She has a doctor\'s appointment later.', chinese: '她稍后要去看医生。', scenario: '早晨送园' },
  { id: 'cc-9', english: 'She might be tired from the trip.', chinese: '她可能因为路途而有点累。', scenario: '早晨送园' },
  { id: 'cc-10', english: 'She needs her medication at noon.', chinese: '她中午需要服药。', scenario: '早晨送园' },
  { id: 'cc-11', english: 'Here is her water bottle.', chinese: '这是她的水壶。', scenario: '早晨送园' },
  { id: 'cc-12', english: 'Thanks for looking after her.', chinese: '谢谢照顾她。', scenario: '早晨送园' },
  // 下午接孩子
  { id: 'cc-13', english: 'How was her day?', chinese: '她今天过得怎么样？', scenario: '下午接孩子' },
  { id: 'cc-14', english: 'Did she eat well today?', chinese: '她今天吃得好吗？', scenario: '下午接孩子' },
  { id: 'cc-15', english: 'Did she have a nap?', chinese: '她午睡了吗？', scenario: '下午接孩子' },
  { id: 'cc-16', english: 'Did she play nicely with others?', chinese: '她和其他孩子玩得好吗？', scenario: '下午接孩子' },
  { id: 'cc-17', english: 'Did she have any accidents?', chinese: '她有发生什么意外吗？', scenario: '下午接孩子' },
  { id: 'cc-18', english: 'Does she have any artwork or crafts to take home?', chinese: '有作品带回家吗？', scenario: '下午接孩子' },
  { id: 'cc-19', english: 'Is there anything we need to work on?', chinese: '有没有需要我们配合的事情？', scenario: '下午接孩子' },
  { id: 'cc-20', english: 'When is the next event?', chinese: '下一次活动是什么时候？', scenario: '下午接孩子' },
  { id: 'cc-21', english: 'Did she drink enough water?', chinese: '她喝了足够的水吗？', scenario: '下午接孩子' },
  { id: 'cc-22', english: 'Any notes for tomorrow?', chinese: '明天有注意事项吗？', scenario: '下午接孩子' },
  { id: 'cc-23', english: 'How was her mood?', chinese: '她的心情怎么样？', scenario: '下午接孩子' },
  { id: 'cc-24', english: 'Thank you, see you tomorrow!', chinese: '谢谢，明天见！', scenario: '下午接孩子' },
  // 饮食沟通
  { id: 'cc-25', english: 'Did she finish her lunch?', chinese: '她把午饭吃完了吗？', scenario: '与老师沟通饮食' },
  { id: 'cc-26', english: 'She doesn\'t like carrots.', chinese: '她不喜欢吃胡萝卜。', scenario: '与老师沟通饮食' },
  { id: 'cc-27', english: 'Could you give her more fruit?', chinese: '能给她多一些水果吗？', scenario: '与老师沟通饮食' },
  { id: 'cc-28', english: 'She is allergic to peanuts.', chinese: '她对花生过敏。', scenario: '与老师沟通饮食' },
  { id: 'cc-29', english: 'Please avoid dairy products.', chinese: '请避免乳制品。', scenario: '与老师沟通饮食' },
  { id: 'cc-30', english: 'She prefers rice over pasta.', chinese: '她比起面食更喜欢米饭。', scenario: '与老师沟通饮食' },
  { id: 'cc-31', english: 'She needs to drink more water.', chinese: '她需要多喝水。', scenario: '与老师沟通饮食' },
  { id: 'cc-32', english: 'Did she try any new foods today?', chinese: '她今天尝试了什么新食物吗？', scenario: '与老师沟通饮食' },
  { id: 'cc-33', english: 'She might be picky today.', chinese: '她今天可能挑食。', scenario: '与老师沟通饮食' },
  { id: 'cc-34', english: 'We packed a snack for her.', chinese: '我们给她准备了零食。', scenario: '与老师沟通饮食' },
  { id: 'cc-35', english: 'Please encourage her to eat vegetables.', chinese: '请鼓励她吃蔬菜。', scenario: '与老师沟通饮食' },
  { id: 'cc-36', english: 'She has a small appetite.', chinese: '她食量不大。', scenario: '与老师沟通饮食' },
  // 睡眠沟通
  { id: 'cc-37', english: 'Did she take a nap?', chinese: '她睡午觉了吗？', scenario: '与老师沟通睡眠' },
  { id: 'cc-38', english: 'How long did she sleep?', chinese: '她睡了多久？', scenario: '与老师沟通睡眠' },
  { id: 'cc-39', english: 'Was she hard to settle?', chinese: '她很难安静下来吗？', scenario: '与老师沟通睡眠' },
  { id: 'cc-40', english: 'She woke up crying.', chinese: '她醒来时哭了。', scenario: '与老师沟通睡眠' },
  { id: 'cc-41', english: 'She had a good nap today.', chinese: '她今天午睡得很好。', scenario: '与老师沟通睡眠' },
  { id: 'cc-42', english: 'She didn\'t nap today.', chinese: '她今天没有午睡。', scenario: '与老师沟通睡眠' },
  { id: 'cc-43', english: 'She fell asleep quickly.', chinese: '她很快就睡着了。', scenario: '与老师沟通睡眠' },
  { id: 'cc-44', english: 'She had a short rest.', chinese: '她休息了一会儿。', scenario: '与老师沟通睡眠' },
  { id: 'cc-45', english: 'Please let her sleep longer if possible.', chinese: '如果可以，请让她多睡一会儿。', scenario: '与老师沟通睡眠' },
  { id: 'cc-46', english: 'We stayed up late last night.', chinese: '我们昨晚睡得晚。', scenario: '与老师沟通睡眠' },
  { id: 'cc-47', english: 'She uses a comforter to sleep.', chinese: '她睡觉需要抱一个玩具。', scenario: '与老师沟通睡眠' },
  { id: 'cc-48', english: 'She didn\'t want to nap today.', chinese: '她今天不想睡午觉。', scenario: '与老师沟通睡眠' },
  // 生病沟通
  { id: 'cc-49', english: 'She has a fever today.', chinese: '她今天发烧了。', scenario: '与老师沟通生病' },
  { id: 'cc-50', english: 'She has a runny nose.', chinese: '她流鼻涕。', scenario: '与老师沟通生病' },
  { id: 'cc-51', english: 'She was coughing this morning.', chinese: '她今天早上咳嗽。', scenario: '与老师沟通生病' },
  { id: 'cc-52', english: 'She feels better now.', chinese: '她现在感觉好多了。', scenario: '与老师沟通生病' },
  { id: 'cc-53', english: 'Please monitor her temperature.', chinese: '请监测她的体温。', scenario: '与老师沟通生病' },
  { id: 'cc-54', english: 'She vomited once.', chinese: '她呕吐过一次。', scenario: '与老师沟通生病' },
  { id: 'cc-55', english: 'She is on antibiotics.', chinese: '她在服用抗生素。', scenario: '与老师沟通生病' },
  { id: 'cc-56', english: 'Please call me if she gets worse.', chinese: '如果她病情加重请打电话给我。', scenario: '与老师沟通生病' },
  { id: 'cc-57', english: 'She might be contagious.', chinese: '她可能会传染。', scenario: '与老师沟通生病' },
  { id: 'cc-58', english: 'She has an upset stomach.', chinese: '她肚子不舒服。', scenario: '与老师沟通生病' },
  { id: 'cc-59', english: 'She scratched herself.', chinese: '她抓伤了自己。', scenario: '与老师沟通生病' },
  { id: 'cc-60', english: 'She has been feeling tired.', chinese: '她感到疲倦。', scenario: '与老师沟通生病' },
  // 请假
  { id: 'cc-61', english: 'She will be absent tomorrow.', chinese: '她明天不会来。', scenario: '请假' },
  { id: 'cc-62', english: 'We are going on a holiday next week.', chinese: '我们下周去度假。', scenario: '请假' },
  { id: 'cc-63', english: 'She will be late today.', chinese: '她今天会迟到。', scenario: '请假' },
  { id: 'cc-64', english: 'We need to pick her up early.', chinese: '我们需要提前接她。', scenario: '请假' },
  { id: 'cc-65', english: 'She will return on Monday.', chinese: '她周一回来。', scenario: '请假' },
  { id: 'cc-66', english: 'Please excuse her absence.', chinese: '请批准她的请假。', scenario: '请假' },
  { id: 'cc-67', english: 'We have a doctor\'s appointment.', chinese: '我们要去看医生。', scenario: '请假' },
  { id: 'cc-68', english: 'She has family visiting.', chinese: '有家人来访。', scenario: '请假' },
  { id: 'cc-69', english: 'She is not feeling well, so she will stay at home.', chinese: '她不舒服，所以会在家。', scenario: '请假' },
  { id: 'cc-70', english: 'We will travel overseas.', chinese: '我们要去国外。', scenario: '请假' },
  { id: 'cc-71', english: 'She will miss the event.', chinese: '她将错过这次活动。', scenario: '请假' },
  { id: 'cc-72', english: 'Please record her leave.', chinese: '请记录她的请假。', scenario: '请假' },
  // 询问孩子表现
  { id: 'cc-73', english: 'Did she participate in class?', chinese: '她有参加课堂活动吗？', scenario: '询问孩子表现' },
  { id: 'cc-74', english: 'Did she listen well?', chinese: '她有认真听讲吗？', scenario: '询问孩子表现' },
  { id: 'cc-75', english: 'She was very helpful today.', chinese: '她今天很乐于助人。', scenario: '询问孩子表现' },
  { id: 'cc-76', english: 'She shared her toys.', chinese: '她分享了自己的玩具。', scenario: '询问孩子表现' },
  { id: 'cc-77', english: 'She followed instructions.', chinese: '她遵循了指令。', scenario: '询问孩子表现' },
  { id: 'cc-78', english: 'She needed some help with tasks.', chinese: '她需要一些帮助。', scenario: '询问孩子表现' },
  { id: 'cc-79', english: 'She seemed upset.', chinese: '她看起来有些沮丧。', scenario: '询问孩子表现' },
  { id: 'cc-80', english: 'She enjoyed singing.', chinese: '她喜欢唱歌。', scenario: '询问孩子表现' },
  { id: 'cc-81', english: 'She was very energetic.', chinese: '她非常有活力。', scenario: '询问孩子表现' },
  { id: 'cc-82', english: 'She had trouble focusing.', chinese: '她注意力不集中。', scenario: '询问孩子表现' },
  { id: 'cc-83', english: 'She learned some new words.', chinese: '她学了几个新词。', scenario: '询问孩子表现' },
  { id: 'cc-84', english: 'She loved story time.', chinese: '她喜欢听故事。', scenario: '询问孩子表现' },
  // 参加活动
  { id: 'cc-85', english: 'She painted a picture.', chinese: '她画了一幅画。', scenario: '参加活动' },
  { id: 'cc-86', english: 'She played outside.', chinese: '她在外面玩。', scenario: '参加活动' },
  { id: 'cc-87', english: 'She built a tower with blocks.', chinese: '她用积木搭了一个塔。', scenario: '参加活动' },
  { id: 'cc-88', english: 'She played in the sandpit.', chinese: '她在沙坑里玩。', scenario: '参加活动' },
  { id: 'cc-89', english: 'She enjoyed the music session.', chinese: '她很喜欢音乐时间。', scenario: '参加活动' },
  { id: 'cc-90', english: 'She participated in group games.', chinese: '她参加了集体游戏。', scenario: '参加活动' },
  { id: 'cc-91', english: 'She planted a seed.', chinese: '她种了一颗种子。', scenario: '参加活动' },
  { id: 'cc-92', english: 'She danced with her friends.', chinese: '她和朋友跳舞。', scenario: '参加活动' },
  { id: 'cc-93', english: 'She made a craft.', chinese: '她做了手工。', scenario: '参加活动' },
  { id: 'cc-94', english: 'She practiced letters.', chinese: '她练习写字母。', scenario: '参加活动' },
  { id: 'cc-95', english: 'She read books with the teacher.', chinese: '她和老师一起读书。', scenario: '参加活动' },
  { id: 'cc-96', english: 'She did yoga.', chinese: '她做了瑜伽。', scenario: '参加活动' },
  // 家长会沟通
  { id: 'cc-97', english: 'We would like to discuss her progress.', chinese: '我们想讨论她的进步。', scenario: '家长会沟通' },
  { id: 'cc-98', english: 'She is improving her social skills.', chinese: '她的社交能力在进步。', scenario: '家长会沟通' },
  { id: 'cc-99', english: 'We recommend more reading at home.', chinese: '我们建议在家多读书。', scenario: '家长会沟通' },
  { id: 'cc-100', english: 'She enjoys art activities.', chinese: '她喜欢艺术活动。', scenario: '家长会沟通' },
  { id: 'cc-101', english: 'She needs more practice with numbers.', chinese: '她需要更多数字练习。', scenario: '家长会沟通' },
  { id: 'cc-102', english: 'Her speech is developing well.', chinese: '她的语言发展很好。', scenario: '家长会沟通' },
  { id: 'cc-103', english: 'She is very kind to others.', chinese: '她对别人很友好。', scenario: '家长会沟通' },
  { id: 'cc-104', english: 'We are concerned about her attention span.', chinese: '我们担心她的注意力。', scenario: '家长会沟通' },
  { id: 'cc-105', english: 'She is adjusting well to the routine.', chinese: '她适应了日常安排。', scenario: '家长会沟通' },
  { id: 'cc-106', english: 'Let\'s set some goals together.', chinese: '让我们一起设定目标。', scenario: '家长会沟通' },
  { id: 'cc-107', english: 'She could benefit from more outdoor play.', chinese: '她可以多参加户外活动。', scenario: '家长会沟通' },
  { id: 'cc-108', english: 'We are happy with her progress.', chinese: '我们对她的进步感到满意。', scenario: '家长会沟通' }
];

// 护理英语（Nursing English）
const nursingData = [
  // Vital Signs (生命体征)
  { id: 'n-1', english: 'Please sit still while I take your blood pressure.', chinese: '请坐好，我要测量您的血压。', scenario: 'Vital Signs' },
  { id: 'n-2', english: 'Can you roll up your sleeve?', chinese: '请把袖子卷起来。', scenario: 'Vital Signs' },
  { id: 'n-3', english: 'Your temperature is a little high.', chinese: '您的体温有点高。', scenario: 'Vital Signs' },
  { id: 'n-4', english: 'I will check your pulse.', chinese: '我来测一下您的脉搏。', scenario: 'Vital Signs' },
  { id: 'n-5', english: 'Take a deep breath for me.', chinese: '请深呼吸。', scenario: 'Vital Signs' },
  { id: 'n-6', english: 'Let me listen to your lungs.', chinese: '让我听听您的肺部。', scenario: 'Vital Signs' },
  { id: 'n-7', english: 'Your oxygen level is normal.', chinese: '您的血氧水平正常。', scenario: 'Vital Signs' },
  { id: 'n-8', english: 'Hold out your arm.', chinese: '请伸出手臂。', scenario: 'Vital Signs' },
  { id: 'n-9', english: 'Have you been feeling dizzy?', chinese: '您最近有没有头晕？', scenario: 'Vital Signs' },
  { id: 'n-10', english: 'Do you feel any pain?', chinese: '您觉得疼吗？', scenario: 'Vital Signs' },
  { id: 'n-11', english: 'Your blood pressure is low.', chinese: '您的血压有点低。', scenario: 'Vital Signs' },
  { id: 'n-12', english: 'I need to take your weight.', chinese: '我需要测量您的体重。', scenario: 'Vital Signs' },
  { id: 'n-13', english: 'Please stand on the scale.', chinese: '请站在秤上。', scenario: 'Vital Signs' },
  { id: 'n-14', english: 'How many times have you vomited?', chinese: '您呕吐了几次？', scenario: 'Vital Signs' },
  { id: 'n-15', english: 'Have you had any fever?', chinese: '您有发烧吗？', scenario: 'Vital Signs' },
  { id: 'n-16', english: 'Your heart rate is irregular.', chinese: '您的心率不规律。', scenario: 'Vital Signs' },
  { id: 'n-17', english: 'I will check your blood sugar.', chinese: '我来测一下您的血糖。', scenario: 'Vital Signs' },
  { id: 'n-18', english: 'Did you fast this morning?', chinese: '您今天早上空腹了吗？', scenario: 'Vital Signs' },
  { id: 'n-19', english: "I'm going to take your temperature under your tongue.", chinese: '我要把体温计放在您的舌下。', scenario: 'Vital Signs' },
  { id: 'n-20', english: 'Please lie down for a few minutes.', chinese: '请躺几分钟。', scenario: 'Vital Signs' },
  { id: 'n-21', english: 'I will check your respiration rate.', chinese: '我来测一下您的呼吸频率。', scenario: 'Vital Signs' },
  { id: 'n-22', english: 'Please relax your arm.', chinese: '请放松手臂。', scenario: 'Vital Signs' },
  { id: 'n-23', english: 'Your pulse is strong.', chinese: '您的脉搏很强。', scenario: 'Vital Signs' },
  { id: 'n-24', english: 'Your vital signs are stable.', chinese: '您的生命体征稳定。', scenario: 'Vital Signs' },
  { id: 'n-25', english: 'We will monitor you closely.', chinese: '我们会密切监测您。', scenario: 'Vital Signs' },
  // Medication Administration (用药管理)
  { id: 'n-26', english: 'Have you taken this medication before?', chinese: '您以前服用过这种药吗？', scenario: 'Medication Administration' },
  { id: 'n-27', english: 'Here is your pain medication.', chinese: '这是您的止痛药。', scenario: 'Medication Administration' },
  { id: 'n-28', english: 'Do you have any allergies to medications?', chinese: '您对药物过敏吗？', scenario: 'Medication Administration' },
  { id: 'n-29', english: 'Take this pill with water.', chinese: '用水服下这片药。', scenario: 'Medication Administration' },
  { id: 'n-30', english: 'This injection may sting a little.', chinese: '这个注射可能会有点疼。', scenario: 'Medication Administration' },
  { id: 'n-31', english: "I'm going to give you an IV drip.", chinese: '我要给您挂点滴。', scenario: 'Medication Administration' },
  { id: 'n-32', english: 'Let me clean the injection site.', chinese: '让我清洁一下注射部位。', scenario: 'Medication Administration' },
  { id: 'n-33', english: 'You need this antibiotic twice a day.', chinese: '您需要每天服用两次这种抗生素。', scenario: 'Medication Administration' },
  { id: 'n-34', english: 'Please finish the whole course.', chinese: '请完成整个疗程。', scenario: 'Medication Administration' },
  { id: 'n-35', english: 'Have you experienced any side effects?', chinese: '您有任何副作用吗？', scenario: 'Medication Administration' },
  { id: 'n-36', english: "Don't operate machinery after taking this.", chinese: '服用后请勿操作机器。', scenario: 'Medication Administration' },
  { id: 'n-37', english: 'We will adjust your dosage.', chinese: '我们会调整您的剂量。', scenario: 'Medication Administration' },
  { id: 'n-38', english: 'Please swallow the tablet whole.', chinese: '请整片吞服。', scenario: 'Medication Administration' },
  { id: 'n-39', english: 'This medicine should be taken with food.', chinese: '这种药需要随餐服用。', scenario: 'Medication Administration' },
  { id: 'n-40', english: "I'll show you how to use the inhaler.", chinese: '我教您如何使用吸入器。', scenario: 'Medication Administration' },
  { id: 'n-41', english: 'Do not drink alcohol with this medication.', chinese: '服用该药期间请不要喝酒。', scenario: 'Medication Administration' },
  { id: 'n-42', english: 'Take one tablet every 6 hours.', chinese: '每六小时服用一片。', scenario: 'Medication Administration' },
  { id: 'n-43', english: "I'm going to flush your IV line.", chinese: '我要冲洗您的静脉线路。', scenario: 'Medication Administration' },
  { id: 'n-44', english: 'Let me double-check your chart.', chinese: '让我再核对一下您的病历。', scenario: 'Medication Administration' },
  { id: 'n-45', english: 'Please hold the cotton on the injection site.', chinese: '请按住注射部位的棉球。', scenario: 'Medication Administration' },
  { id: 'n-46', english: 'We need to record the time of administration.', chinese: '我们需要记录用药时间。', scenario: 'Medication Administration' },
  { id: 'n-47', english: "I'll prepare your insulin.", chinese: '我来准备您的胰岛素。', scenario: 'Medication Administration' },
  { id: 'n-48', english: 'Make sure to shake the bottle well.', chinese: '请务必摇匀瓶子。', scenario: 'Medication Administration' },
  { id: 'n-49', english: "Don't miss a dose.", chinese: '不要漏服。', scenario: 'Medication Administration' },
  { id: 'n-50', english: "We'll switch you to oral medication tomorrow.", chinese: '我们明天会换成口服药。', scenario: 'Medication Administration' },
  // Patient Assessment (患者评估)
  { id: 'n-51', english: 'Where is your pain located?', chinese: '您的疼痛在哪里？', scenario: 'Patient Assessment' },
  { id: 'n-52', english: 'On a scale of 1 to 10, how bad is your pain?', chinese: '在1到10的范围内，您的疼痛程度是多少？', scenario: 'Patient Assessment' },
  { id: 'n-53', english: 'Do you feel short of breath?', chinese: '您感觉喘不上气吗？', scenario: 'Patient Assessment' },
  { id: 'n-54', english: 'Have you had any nausea?', chinese: '您有恶心吗？', scenario: 'Patient Assessment' },
  { id: 'n-55', english: 'Are you able to eat?', chinese: '您能吃东西吗？', scenario: 'Patient Assessment' },
  { id: 'n-56', english: 'Can you walk to the bathroom?', chinese: '您可以走到卫生间吗？', scenario: 'Patient Assessment' },
  { id: 'n-57', english: 'Have you been passing urine normally?', chinese: '您的排尿正常吗？', scenario: 'Patient Assessment' },
  { id: 'n-58', english: 'Are you feeling weak?', chinese: '您觉得虚弱吗？', scenario: 'Patient Assessment' },
  { id: 'n-59', english: 'Do you have any swelling?', chinese: '您有肿胀吗？', scenario: 'Patient Assessment' },
  { id: 'n-60', english: 'When did the pain start?', chinese: '疼痛是什么时候开始的？', scenario: 'Patient Assessment' },
  { id: 'n-61', english: 'Is the pain sharp or dull?', chinese: '疼痛是尖锐的还是钝痛？', scenario: 'Patient Assessment' },
  { id: 'n-62', english: 'Does anything make it better?', chinese: '有什么能缓解疼痛吗？', scenario: 'Patient Assessment' },
  { id: 'n-63', english: 'Are you currently taking any medication?', chinese: '您目前在服用任何药物吗？', scenario: 'Patient Assessment' },
  { id: 'n-64', english: 'Do you have any allergies?', chinese: '您有过敏史吗？', scenario: 'Patient Assessment' },
  { id: 'n-65', english: 'Have you had surgery before?', chinese: '您做过手术吗？', scenario: 'Patient Assessment' },
  { id: 'n-66', english: 'Can you rate your level of fatigue?', chinese: '您能评估一下自己的疲劳程度吗？', scenario: 'Patient Assessment' },
  { id: 'n-67', english: 'Do you have any numbness?', chinese: '您有麻木感吗？', scenario: 'Patient Assessment' },
  { id: 'n-68', english: 'Are you feeling anxious?', chinese: '您觉得焦虑吗？', scenario: 'Patient Assessment' },
  { id: 'n-69', english: 'When was your last bowel movement?', chinese: '您上次排便是什么时候？', scenario: 'Patient Assessment' },
  { id: 'n-70', english: 'Are you feeling dizzy when standing?', chinese: '您站起来时会头晕吗？', scenario: 'Patient Assessment' },
  { id: 'n-71', english: 'How is your appetite?', chinese: '您的食欲如何？', scenario: 'Patient Assessment' },
  { id: 'n-72', english: 'Do you have trouble sleeping?', chinese: '您睡眠有困难吗？', scenario: 'Patient Assessment' },
  { id: 'n-73', english: 'Have you lost weight recently?', chinese: '您最近有体重下降吗？', scenario: 'Patient Assessment' },
  { id: 'n-74', english: 'Does the pain radiate to other parts of your body?', chinese: '疼痛会扩散到身体其他部位吗？', scenario: 'Patient Assessment' },
  { id: 'n-75', english: 'Is your vision blurry?', chinese: '您的视力模糊吗？', scenario: 'Patient Assessment' },
  // Clinical Placement (临床实习)
  { id: 'n-76', english: "Let's wash our hands first.", chinese: '让我们先洗手。', scenario: 'Clinical Placement' },
  { id: 'n-77', english: 'Please put on gloves.', chinese: '请戴上手套。', scenario: 'Clinical Placement' },
  { id: 'n-78', english: "We'll perform wound dressing now.", chinese: '我们现在为伤口换药。', scenario: 'Clinical Placement' },
  { id: 'n-79', english: 'Observe how to insert a catheter.', chinese: '观察如何插入导尿管。', scenario: 'Clinical Placement' },
  { id: 'n-80', english: 'Remember to maintain patient privacy.', chinese: '记得要保持患者隐私。', scenario: 'Clinical Placement' },
  { id: 'n-81', english: 'Check the patient\'s ID band.', chinese: '检查患者的腕带。', scenario: 'Clinical Placement' },
  { id: 'n-82', english: "We'll change the bed linen.", chinese: '我们要换床单。', scenario: 'Clinical Placement' },
  { id: 'n-83', english: 'Help me turn the patient.', chinese: '帮我翻身病人。', scenario: 'Clinical Placement' },
  { id: 'n-84', english: 'Monitor the IV fluid rate.', chinese: '监测静脉输液速度。', scenario: 'Clinical Placement' },
  { id: 'n-85', english: "Chart the patient's intake and output.", chinese: '记录患者的摄入和排出。', scenario: 'Clinical Placement' },
  { id: 'n-86', english: 'Practice taking blood samples.', chinese: '练习采血。', scenario: 'Clinical Placement' },
  { id: 'n-87', english: "Don't forget to label specimens.", chinese: '别忘了标记样本。', scenario: 'Clinical Placement' },
  { id: 'n-88', english: 'Keep sharp objects in the sharps container.', chinese: '将尖锐物放入专用回收桶。', scenario: 'Clinical Placement' },
  { id: 'n-89', english: 'Disinfect the equipment after use.', chinese: '使用后要消毒设备。', scenario: 'Clinical Placement' },
  { id: 'n-90', english: 'Follow the aseptic technique.', chinese: '遵循无菌操作。', scenario: 'Clinical Placement' },
  { id: 'n-91', english: 'We need to update the care plan.', chinese: '我们需要更新护理计划。', scenario: 'Clinical Placement' },
  { id: 'n-92', english: 'Check the medication order with a nurse.', chinese: '与护士核对用药医嘱。', scenario: 'Clinical Placement' },
  { id: 'n-93', english: 'Document everything accurately.', chinese: '准确记录一切。', scenario: 'Clinical Placement' },
  { id: 'n-94', english: 'Stay calm during emergencies.', chinese: '在紧急情况下保持冷静。', scenario: 'Clinical Placement' },
  { id: 'n-95', english: 'Ask for help when you need it.', chinese: '需要帮助时请寻求支持。', scenario: 'Clinical Placement' },
  { id: 'n-96', english: 'Learn to prioritize tasks.', chinese: '学会为任务排序。', scenario: 'Clinical Placement' },
  { id: 'n-97', english: 'Communicate clearly with the patient.', chinese: '与患者沟通要清晰。', scenario: 'Clinical Placement' },
  { id: 'n-98', english: "We'll do a head-to-toe assessment.", chinese: '我们将做一个从头到脚的评估。', scenario: 'Clinical Placement' },
  { id: 'n-99', english: 'Always double-check the dosage.', chinese: '务必核对剂量。', scenario: 'Clinical Placement' },
  { id: 'n-100', english: 'Reflect on your practice daily.', chinese: '每天反思你的实践。', scenario: 'Clinical Placement' },
  // Handover (交接班)
  { id: 'n-101', english: 'The patient in bed 3 is stable.', chinese: '3号床的病人情况稳定。', scenario: 'Handover' },
  { id: 'n-102', english: 'She had pain overnight.', chinese: '她昨晚疼痛。', scenario: 'Handover' },
  { id: 'n-103', english: 'Her blood pressure dropped this morning.', chinese: '她今天早上血压下降。', scenario: 'Handover' },
  { id: 'n-104', english: 'We administered morphine at 6 am.', chinese: '我们早上6点给她注射了吗啡。', scenario: 'Handover' },
  { id: 'n-105', english: 'She is allergic to penicillin.', chinese: '她对青霉素过敏。', scenario: 'Handover' },
  { id: 'n-106', english: 'She will have an X-ray at noon.', chinese: '她中午要做X光检查。', scenario: 'Handover' },
  { id: 'n-107', english: 'Her family visited this afternoon.', chinese: '她的家人今天下午来看望。', scenario: 'Handover' },
  { id: 'n-108', english: 'She refused her medication.', chinese: '她拒绝服药。', scenario: 'Handover' },
  { id: 'n-109', english: 'She is nil by mouth.', chinese: '她禁食禁水。', scenario: 'Handover' },
  { id: 'n-110', english: 'Please monitor her urine output.', chinese: '请监测她的尿量。', scenario: 'Handover' },
  { id: 'n-111', english: 'She vomited twice last night.', chinese: '她昨晚呕吐了两次。', scenario: 'Handover' },
  { id: 'n-112', english: 'She is due for her next dose at 10 pm.', chinese: '她下一次用药时间是晚上10点。', scenario: 'Handover' },
  { id: 'n-113', english: 'She has an IV cannula in the right arm.', chinese: '她右臂有静脉套管。', scenario: 'Handover' },
  { id: 'n-114', english: 'Her wound dressing is intact.', chinese: '她的伤口敷料完好。', scenario: 'Handover' },
  { id: 'n-115', english: 'She is waiting for blood test results.', chinese: '她在等待血检结果。', scenario: 'Handover' },
  { id: 'n-116', english: 'Please encourage her to mobilize.', chinese: '请鼓励她下床活动。', scenario: 'Handover' },
  { id: 'n-117', english: 'She is on a fluid restriction.', chinese: '她需要限制液体摄入。', scenario: 'Handover' },
  { id: 'n-118', english: 'She had a fall last week.', chinese: '她上周摔倒了。', scenario: 'Handover' },
  { id: 'n-119', english: 'She is diabetic.', chinese: '她是糖尿病患者。', scenario: 'Handover' },
  { id: 'n-120', english: 'She has been restless.', chinese: '她一直不安。', scenario: 'Handover' },
  { id: 'n-121', english: 'She is scheduled for surgery tomorrow.', chinese: '她计划明天手术。', scenario: 'Handover' },
  { id: 'n-122', english: 'She needs assistance to shower.', chinese: '她需要协助洗澡。', scenario: 'Handover' },
  { id: 'n-123', english: 'Please update her care plan.', chinese: '请更新她的护理计划。', scenario: 'Handover' },
  { id: 'n-124', english: 'She ate 50% of her meal.', chinese: '她吃了50%的饭。', scenario: 'Handover' },
  { id: 'n-125', english: 'She is on oxygen via nasal prongs.', chinese: '她通过鼻塞吸氧。', scenario: 'Handover' },
  // SBAR Communication (SBAR沟通)
  { id: 'n-126', english: 'Situation: The patient is complaining of chest pain.', chinese: '情境：病人胸痛。', scenario: 'SBAR Communication' },
  { id: 'n-127', english: 'Background: She has a history of heart disease.', chinese: '背景：她有心脏病史。', scenario: 'SBAR Communication' },
  { id: 'n-128', english: 'Assessment: Her blood pressure is 90/60 and pulse is 110.', chinese: '评估：她的血压是90/60，脉搏110。', scenario: 'SBAR Communication' },
  { id: 'n-129', english: 'Recommendation: I think she needs to be reviewed urgently.', chinese: '建议：我认为需要紧急会诊。', scenario: 'SBAR Communication' },
  { id: 'n-130', english: 'Situation: The wound site is red and swollen.', chinese: '情境：伤口处红肿。', scenario: 'SBAR Communication' },
  { id: 'n-131', english: 'Background: He had surgery two days ago.', chinese: '背景：他两天前做了手术。', scenario: 'SBAR Communication' },
  { id: 'n-132', english: 'Assessment: His temperature is 38.5 °C.', chinese: '评估：他的体温是38.5摄氏度。', scenario: 'SBAR Communication' },
  { id: 'n-133', english: 'Recommendation: Should we start antibiotics?', chinese: '建议：我们是否应该开始抗生素？', scenario: 'SBAR Communication' },
  { id: 'n-134', english: 'Situation: Patient’s blood sugar is low.', chinese: '情境：病人的血糖低。', scenario: 'SBAR Communication' },
  { id: 'n-135', english: 'Background: She is on insulin therapy.', chinese: '背景：她正在接受胰岛素治疗。', scenario: 'SBAR Communication' },
  { id: 'n-136', english: 'Assessment: She looks pale and sweaty.', chinese: '评估：她看起来苍白且冒汗。', scenario: 'SBAR Communication' },
  { id: 'n-137', english: 'Recommendation: Would you like me to give glucose?', chinese: '建议：您需要我给她补充葡萄糖吗？', scenario: 'SBAR Communication' },
  { id: 'n-138', english: 'Situation: He is short of breath.', chinese: '情境：他呼吸困难。', scenario: 'SBAR Communication' },
  { id: 'n-139', english: 'Background: He has chronic obstructive pulmonary disease.', chinese: '背景：他有慢性阻塞性肺病。', scenario: 'SBAR Communication' },
  { id: 'n-140', english: 'Assessment: Oxygen saturation is 88% on room air.', chinese: '评估：室内空气下血氧饱和度88%。', scenario: 'SBAR Communication' },
  { id: 'n-141', english: 'Recommendation: Shall we increase oxygen?', chinese: '建议：是否要提高氧流量？', scenario: 'SBAR Communication' },
  { id: 'n-142', english: 'Situation: She hasn\'t passed urine for 8 hours.', chinese: '情境：她8小时未排尿。', scenario: 'SBAR Communication' },
  { id: 'n-143', english: 'Background: She had surgery this morning.', chinese: '背景：她今天早上做了手术。', scenario: 'SBAR Communication' },
  { id: 'n-144', english: 'Assessment: Her bladder is full.', chinese: '评估：她的膀胱胀满。', scenario: 'SBAR Communication' },
  { id: 'n-145', english: 'Recommendation: Should we insert a catheter?', chinese: '建议：我们是否插导尿管？', scenario: 'SBAR Communication' },
  { id: 'n-146', english: 'Situation: Patient is confused and agitated.', chinese: '情境：病人困惑且激动。', scenario: 'SBAR Communication' },
  { id: 'n-147', english: 'Background: He has dementia.', chinese: '背景：他患有痴呆症。', scenario: 'SBAR Communication' },
  { id: 'n-148', english: 'Assessment: He tried to climb out of bed.', chinese: '评估：他试图下床。', scenario: 'SBAR Communication' },
  { id: 'n-149', english: 'Recommendation: Can we review his sedation?', chinese: '建议：我们要调整他的镇静药吗？', scenario: 'SBAR Communication' },
  { id: 'n-150', english: 'Situation: The IV site is leaking.', chinese: '情境：静脉注射部位漏液。', scenario: 'SBAR Communication' },
  { id: 'n-151', english: 'Background: She has been on IV fluids for 24 hours.', chinese: '背景：她已经输液24小时。', scenario: 'SBAR Communication' },
  { id: 'n-152', english: 'Assessment: The cannula may be dislodged.', chinese: '评估：套管可能脱落。', scenario: 'SBAR Communication' },
  { id: 'n-153', english: 'Recommendation: Shall we replace the cannula?', chinese: '建议：是否更换套管？', scenario: 'SBAR Communication' },
  { id: 'n-154', english: 'Situation: The patient fell in the bathroom.', chinese: '情境：病人在卫生间摔倒。', scenario: 'SBAR Communication' },
  { id: 'n-155', english: 'Background: He is frail and uses a walking frame.', chinese: '背景：他身体虚弱，使用助行架。', scenario: 'SBAR Communication' },
  { id: 'n-156', english: 'Assessment: He has a bruise on his hip.', chinese: '评估：他臀部有瘀伤。', scenario: 'SBAR Communication' },
  { id: 'n-157', english: 'Recommendation: Should we order an X-ray?', chinese: '建议：我们是否要做X光？', scenario: 'SBAR Communication' },
  { id: 'n-158', english: 'Situation: The medication chart is unclear.', chinese: '情境：药物记录不清晰。', scenario: 'SBAR Communication' },
  { id: 'n-159', english: 'Background: There are two orders for pain relief.', chinese: '背景：有两个止痛医嘱。', scenario: 'SBAR Communication' },
  { id: 'n-160', english: 'Assessment: There is a risk of overdose.', chinese: '评估：可能会过量。', scenario: 'SBAR Communication' },
  { id: 'n-161', english: 'Recommendation: Please clarify the orders.', chinese: '建议：请澄清医嘱。', scenario: 'SBAR Communication' },
  { id: 'n-162', english: 'Situation: His blood pressure remains high.', chinese: '情境：他的血压持续偏高。', scenario: 'SBAR Communication' },
  { id: 'n-163', english: 'Background: He was given antihypertensive medication.', chinese: '背景：他服用了降压药。', scenario: 'SBAR Communication' },
  { id: 'n-164', english: 'Assessment: BP is 170/100.', chinese: '评估：血压为170/100。', scenario: 'SBAR Communication' },
  { id: 'n-165', english: 'Recommendation: Should we increase the dose?', chinese: '建议：是否增加剂量？', scenario: 'SBAR Communication' },
  // Aged Care (养老护理)
  { id: 'n-166', english: 'Please take your time, there is no rush.', chinese: '请慢慢来，不着急。', scenario: 'Aged Care' },
  { id: 'n-167', english: 'Can I help you with your meal?', chinese: '我可以帮您吃饭吗？', scenario: 'Aged Care' },
  { id: 'n-168', english: 'Would you like to sit in the lounge?', chinese: '您想坐在休息室吗？', scenario: 'Aged Care' },
  { id: 'n-169', english: 'Do you need assistance with bathing?', chinese: '您需要帮忙洗澡吗？', scenario: 'Aged Care' },
  { id: 'n-170', english: 'Remember to use your walking frame.', chinese: '记得使用您的助行架。', scenario: 'Aged Care' },
  { id: 'n-171', english: "Let's join the group exercise.", chinese: '让我们一起参加集体锻炼。', scenario: 'Aged Care' },
  { id: 'n-172', english: 'How did you sleep last night?', chinese: '您昨晚睡得怎么样？', scenario: 'Aged Care' },
  { id: 'n-173', english: 'Would you like me to read to you?', chinese: '您想让我读书给您听吗？', scenario: 'Aged Care' },
  { id: 'n-174', english: "It's time for your medication.", chinese: '到吃药时间了。', scenario: 'Aged Care' },
  { id: 'n-175', english: 'Are you feeling lonely?', chinese: '您感到孤单吗？', scenario: 'Aged Care' },
  { id: 'n-176', english: 'Do you have any pain?', chinese: '您有疼痛吗？', scenario: 'Aged Care' },
  { id: 'n-177', english: 'Can I adjust your pillow?', chinese: '我可以给您调整枕头吗？', scenario: 'Aged Care' },
  { id: 'n-178', english: 'Do you need to go to the bathroom?', chinese: '您需要去卫生间吗？', scenario: 'Aged Care' },
  { id: 'n-179', english: 'Your family will visit soon.', chinese: '您的家人很快会来看您。', scenario: 'Aged Care' },
  { id: 'n-180', english: "It's important to drink water.", chinese: '多喝水很重要。', scenario: 'Aged Care' },
  { id: 'n-181', english: 'We have art class this afternoon.', chinese: '我们下午有美术课。', scenario: 'Aged Care' },
  { id: 'n-182', english: "Let's put on your glasses.", chinese: '我们把眼镜戴上。', scenario: 'Aged Care' },
  { id: 'n-183', english: 'Would you like some tea?', chinese: '您想喝点茶吗？', scenario: 'Aged Care' },
  { id: 'n-184', english: 'Please ring the bell if you need help.', chinese: '需要帮助请按铃。', scenario: 'Aged Care' },
  { id: 'n-185', english: "I'll help you to stand up.", chinese: '我来扶您站起来。', scenario: 'Aged Care' },
  { id: 'n-186', english: 'Please move carefully.', chinese: '请慢慢移动。', scenario: 'Aged Care' },
  { id: 'n-187', english: 'Would you like to call your family?', chinese: '您想打电话给家人吗？', scenario: 'Aged Care' },
  { id: 'n-188', english: 'Do you prefer to stay in your room?', chinese: '您想留在房间里吗？', scenario: 'Aged Care' },
  { id: 'n-189', english: "Let's go for a short walk.", chinese: '我们去散个步吧。', scenario: 'Aged Care' },
  { id: 'n-190', english: 'Can I help you with your hearing aid?', chinese: '我能帮您调整助听器吗？', scenario: 'Aged Care' },
  // Hospital Communication (医院沟通)
  { id: 'n-191', english: 'Welcome to the ward.', chinese: '欢迎来到病房。', scenario: 'Hospital Communication' },
  { id: 'n-192', english: 'We need to take your details.', chinese: '我们需要登记您的信息。', scenario: 'Hospital Communication' },
  { id: 'n-193', english: 'Please lie down on the bed.', chinese: '请躺在床上。', scenario: 'Hospital Communication' },
  { id: 'n-194', english: 'Do you have your Medicare card?', chinese: '您带了医保卡吗？', scenario: 'Hospital Communication' },
  { id: 'n-195', english: 'How can I assist you?', chinese: '我能为您做些什么？', scenario: 'Hospital Communication' },
  { id: 'n-196', english: 'Visiting hours are over.', chinese: '探视时间结束了。', scenario: 'Hospital Communication' },
  { id: 'n-197', english: 'The doctor will see you soon.', chinese: '医生很快会来看您。', scenario: 'Hospital Communication' },
  { id: 'n-198', english: 'Please sign this consent form.', chinese: '请在这份同意书上签字。', scenario: 'Hospital Communication' },
  { id: 'n-199', english: 'You are scheduled for surgery tomorrow.', chinese: '您预定明天手术。', scenario: 'Hospital Communication' },
  { id: 'n-200', english: "We'll take you to radiology.", chinese: '我们会带您去放射科。', scenario: 'Hospital Communication' },
  { id: 'n-201', english: 'Do you have any questions about your treatment?', chinese: '您对治疗有任何问题吗？', scenario: 'Hospital Communication' },
  { id: 'n-202', english: 'We will discharge you today.', chinese: '我们今天会让您出院。', scenario: 'Hospital Communication' },
  { id: 'n-203', english: 'Please follow the physiotherapist’s instructions.', chinese: '请遵循物理治疗师的指导。', scenario: 'Hospital Communication' },
  { id: 'n-204', english: 'Press the call bell if you need assistance.', chinese: '需要帮助请按呼叫铃。', scenario: 'Hospital Communication' },
  { id: 'n-205', english: 'We need to change your dressing.', chinese: '我们需要给您换药。', scenario: 'Hospital Communication' },
  { id: 'n-206', english: "We will need to monitor your heart.", chinese: '我们需要监测您的心脏。', scenario: 'Hospital Communication' },
  { id: 'n-207', english: 'Can I check your identification?', chinese: '我可以核对您的身份吗？', scenario: 'Hospital Communication' },
  { id: 'n-208', english: 'Please fast from midnight.', chinese: '请从午夜开始禁食。', scenario: 'Hospital Communication' },
  { id: 'n-209', english: 'We will draw some blood.', chinese: '我们需要抽血。', scenario: 'Hospital Communication' },
  { id: 'n-210', english: 'You will need to stay overnight.', chinese: '您需要住院一晚。', scenario: 'Hospital Communication' },
  { id: 'n-211', english: 'The pharmacy will deliver your medications.', chinese: '药房会送来药物。', scenario: 'Hospital Communication' },
  { id: 'n-212', english: 'The dietitian will visit you today.', chinese: '营养师今天会来看您。', scenario: 'Hospital Communication' },
  { id: 'n-213', english: 'Please remove any jewellery.', chinese: '请摘掉所有首饰。', scenario: 'Hospital Communication' },
  { id: 'n-214', english: "I'll help you sit up.", chinese: '我来帮您坐起来。', scenario: 'Hospital Communication' },
  { id: 'n-215', english: 'You can go home once the doctor approves.', chinese: '医生批准后您就可以回家。', scenario: 'Hospital Communication' }
];

// 澳洲生活英语（Australian Life）
const lifeData = [
  // 超市购物
  { id: 'life-1', english: 'Where is the bread aisle?', chinese: '面包区在哪里？', scenario: '超市购物' },
  { id: 'life-2', english: 'Is this item on sale?', chinese: '这个商品有折扣吗？', scenario: '超市购物' },
  { id: 'life-3', english: 'Do you have any fresh seafood?', chinese: '有新鲜的海鲜吗？', scenario: '超市购物' },
  { id: 'life-4', english: 'Can I get a discount with my membership card?', chinese: '会员卡有折扣吗？', scenario: '超市购物' },
  { id: 'life-5', english: 'Could you weigh these apples?', chinese: '可以称一下这些苹果吗？', scenario: '超市购物' },
  { id: 'life-6', english: 'Where can I find milk?', chinese: '我在哪里可以找到牛奶？', scenario: '超市购物' },
  { id: 'life-7', english: 'This price seems wrong.', chinese: '这个价格好像不对。', scenario: '超市购物' },
  { id: 'life-8', english: 'Do you sell organic products?', chinese: '你们有卖有机食品吗？', scenario: '超市购物' },
  { id: 'life-9', english: 'Can I return this if it’s faulty?', chinese: '如果有问题可以退货吗？', scenario: '超市购物' },
  { id: 'life-10', english: 'Do you have a bathroom?', chinese: '有洗手间吗？', scenario: '超市购物' },
  { id: 'life-11', english: 'Can you help me reach the top shelf?', chinese: '你能帮我拿最上面的东西吗？', scenario: '超市购物' },
  { id: 'life-12', english: 'Where are the trolleys?', chinese: '购物车在哪里？', scenario: '超市购物' },
  // 咖啡馆点餐
  { id: 'life-13', english: 'I’d like a cappuccino, please.', chinese: '请给我一杯卡布奇诺。', scenario: '咖啡馆点餐' },
  { id: 'life-14', english: 'Can I have a latte with soy milk?', chinese: '我可以要一杯豆奶拿铁吗？', scenario: '咖啡馆点餐' },
  { id: 'life-15', english: 'Do you serve decaf coffee?', chinese: '你们有无咖啡因咖啡吗？', scenario: '咖啡馆点餐' },
  { id: 'life-16', english: 'One flat white to go, thanks.', chinese: '一杯外带澳白，谢谢。', scenario: '咖啡馆点餐' },
  { id: 'life-17', english: 'Can I get some sugar?', chinese: '可以给我一些糖吗？', scenario: '咖啡馆点餐' },
  { id: 'life-18', english: 'Could you add an extra shot?', chinese: '可以加一份浓缩吗？', scenario: '咖啡馆点餐' },
  { id: 'life-19', english: 'What’s the cake of the day?', chinese: '今天的蛋糕是什么？', scenario: '咖啡馆点餐' },
  { id: 'life-20', english: 'Do you have any gluten‑free options?', chinese: '你们有无麸质的选择吗？', scenario: '咖啡馆点餐' },
  { id: 'life-21', english: 'Can I sit outside?', chinese: '我可以坐外面吗？', scenario: '咖啡馆点餐' },
  { id: 'life-22', english: "It's for here, please.", chinese: '在这里用，谢谢。', scenario: '咖啡馆点餐' },
  { id: 'life-23', english: 'Could you heat it up?', chinese: '可以加热吗？', scenario: '咖啡馆点餐' },
  { id: 'life-24', english: 'May I see the menu?', chinese: '可以给我看一下菜单吗？', scenario: '咖啡馆点餐' },
  // 银行办理业务
  { id: 'life-25', english: "I'd like to open a bank account.", chinese: '我想开一个银行账户。', scenario: '银行办理业务' },
  { id: 'life-26', english: 'What documents do I need?', chinese: '我需要什么文件？', scenario: '银行办理业务' },
  { id: 'life-27', english: "I'd like to deposit some cash.", chinese: '我想存一些现金。', scenario: '银行办理业务' },
  { id: 'life-28', english: 'How do I transfer money overseas?', chinese: '我如何汇款到海外？', scenario: '银行办理业务' },
  { id: 'life-29', english: 'Is there a fee for this service?', chinese: '这项服务有手续费吗？', scenario: '银行办理业务' },
  { id: 'life-30', english: 'Can I get a new bank card?', chinese: '我可以办一张新银行卡吗？', scenario: '银行办理业务' },
  { id: 'life-31', english: 'My card was stolen.', chinese: '我的卡被盗了。', scenario: '银行办理业务' },
  { id: 'life-32', english: "I'd like to close my account.", chinese: '我想注销我的账户。', scenario: '银行办理业务' },
  { id: 'life-33', english: 'Where is the nearest ATM?', chinese: '最近的提款机在哪里？', scenario: '银行办理业务' },
  { id: 'life-34', english: 'I forgot my PIN.', chinese: '我忘记了密码。', scenario: '银行办理业务' },
  { id: 'life-35', english: "I'd like to change my address.", chinese: '我想更改地址。', scenario: '银行办理业务' },
  { id: 'life-36', english: 'How long does a transfer take?', chinese: '转账需要多长时间？', scenario: '银行办理业务' },
  // 看病
  { id: 'life-37', english: 'I have an appointment at 10 am.', chinese: '我预约了上午十点。', scenario: '看病' },
  { id: 'life-38', english: "I don't feel well.", chinese: '我觉得不舒服。', scenario: '看病' },
  { id: 'life-39', english: 'I have a fever.', chinese: '我发烧了。', scenario: '看病' },
  { id: 'life-40', english: 'I’m feeling dizzy.', chinese: '我感到头晕。', scenario: '看病' },
  { id: 'life-41', english: 'I have a sore throat.', chinese: '我喉咙痛。', scenario: '看病' },
  { id: 'life-42', english: "I've been coughing a lot.", chinese: '我咳嗽很多。', scenario: '看病' },
  { id: 'life-43', english: 'I'm allergic to penicillin.', chinese: '我对青霉素过敏。', scenario: '看病' },
  { id: 'life-44', english: 'How long will I need to wait?', chinese: '我需要等多久？', scenario: '看病' },
  { id: 'life-45', english: 'Do I need a prescription?', chinese: '我需要处方吗？', scenario: '看病' },
  { id: 'life-46', english: 'Where is the pharmacy?', chinese: '药店在哪里？', scenario: '看病' },
  { id: 'life-47', english: 'How much will the consultation cost?', chinese: '看诊费用是多少？', scenario: '看病' },
  { id: 'life-48', english: 'Can I get a medical certificate?', chinese: '我可以开病假条吗？', scenario: '看病' },
  // 租房
  { id: 'life-49', english: "I'm looking for an apartment to rent.", chinese: '我在找要租的公寓。', scenario: '租房' },
  { id: 'life-50', english: 'How much is the weekly rent?', chinese: '每周租金是多少？', scenario: '租房' },
  { id: 'life-51', english: 'Is electricity included?', chinese: '水电费包括吗？', scenario: '租房' },
  { id: 'life-52', english: 'Can I inspect the property?', chinese: '我可以看房吗？', scenario: '租房' },
  { id: 'life-53', english: 'Is there a bond?', chinese: '需要交押金吗？', scenario: '租房' },
  { id: 'life-54', english: 'When is it available?', chinese: '什么时候可入住？', scenario: '租房' },
  { id: 'life-55', english: 'How many bedrooms does it have?', chinese: '有几个卧室？', scenario: '租房' },
  { id: 'life-56', english: 'Is it furnished?', chinese: '有家具吗？', scenario: '租房' },
  { id: 'life-57', english: 'Are pets allowed?', chinese: '可以养宠物吗？', scenario: '租房' },
  { id: 'life-58', english: 'How long is the lease?', chinese: '租期多长？', scenario: '租房' },
  { id: 'life-59', english: 'Is there parking?', chinese: '有停车位吗？', scenario: '租房' },
  { id: 'life-60', english: 'What public transport is nearby?', chinese: '附近有什么公共交通？', scenario: '租房' },
  // 求职
  { id: 'life-61', english: "I'm looking for a part‑time job.", chinese: '我在找一份兼职工作。', scenario: '求职' },
  { id: 'life-62', english: 'Do I need a resume?', chinese: '我需要简历吗？', scenario: '求职' },
  { id: 'life-63', english: 'When is the application deadline?', chinese: '申请截止日期是什么时候？', scenario: '求职' },
  { id: 'life-64', english: 'Do you sponsor work visas?', chinese: '你们提供工作签证赞助吗？', scenario: '求职' },
  { id: 'life-65', english: 'How many hours per week?', chinese: '每周多少小时？', scenario: '求职' },
  { id: 'life-66', english: "What's the hourly rate?", chinese: '时薪是多少？', scenario: '求职' },
  { id: 'life-67', english: 'Is training provided?', chinese: '提供培训吗？', scenario: '求职' },
  { id: 'life-68', english: 'Where is the workplace located?', chinese: '工作地点在哪里？', scenario: '求职' },
  { id: 'life-69', english: 'Do I need previous experience?', chinese: '我需要之前的经验吗？', scenario: '求职' },
  { id: 'life-70', english: 'Can I work weekends?', chinese: '我可以周末工作吗？', scenario: '求职' },
  { id: 'life-71', english: 'What are the job responsibilities?', chinese: '工作职责是什么？', scenario: '求职' },
  { id: 'life-72', english: 'When could I start?', chinese: '我什么时候可以开始？', scenario: '求职' },
  // 社交聊天
  { id: 'life-73', english: 'How long have you been in Australia?', chinese: '你在澳大利亚多久了？', scenario: '社交聊天' },
  { id: 'life-74', english: 'Where are you from?', chinese: '你来自哪里？', scenario: '社交聊天' },
  { id: 'life-75', english: 'Do you like living here?', chinese: '你喜欢这里的生活吗？', scenario: '社交聊天' },
  { id: 'life-76', english: 'The weather is lovely today.', chinese: '今天的天气很好。', scenario: '社交聊天' },
  { id: 'life-77', english: 'Have you been to the beach?', chinese: '你去过海滩吗？', scenario: '社交聊天' },
  { id: 'life-78', english: 'What do you do for fun?', chinese: '你有什么兴趣爱好？', scenario: '社交聊天' },
  { id: 'life-79', english: 'Do you like Australian food?', chinese: '你喜欢澳大利亚的食物吗？', scenario: '社交聊天' },
  { id: 'life-80', english: 'Have you visited the Blue Mountains?', chinese: '你去过蓝山吗？', scenario: '社交聊天' },
  { id: 'life-81', english: 'Which suburb do you live in?', chinese: '你住在哪个区？', scenario: '社交聊天' },
  { id: 'life-82', english: 'Are you studying or working?', chinese: '你是在学习还是工作？', scenario: '社交聊天' },
  { id: 'life-83', english: 'Do you have any pets?', chinese: '你有宠物吗？', scenario: '社交聊天' },
  { id: 'life-84', english: 'It was nice talking to you.', chinese: '很高兴和你聊天。', scenario: '社交聊天' },
  { id: 'life-85', english: "Let's catch up sometime.", chinese: '我们找时间聚一下。', scenario: '社交聊天' },
  { id: 'life-86', english: 'Do you play any sports?', chinese: '你玩什么运动吗？', scenario: '社交聊天' },
  // 邻里沟通
  { id: 'life-87', english: 'Good morning, how are you?', chinese: '早上好，你好吗？', scenario: '邻里沟通' },
  { id: 'life-88', english: "I'm your new neighbour.", chinese: '我是你的新邻居。', scenario: '邻里沟通' },
  { id: 'life-89', english: 'Let me know if you need anything.', chinese: '如果你需要什么请告诉我。', scenario: '邻里沟通' },
  { id: 'life-90', english: 'Can I borrow some sugar?', chinese: '我可以借点糖吗？', scenario: '邻里沟通' },
  { id: 'life-91', english: 'Your garden looks beautiful.', chinese: '你的花园很漂亮。', scenario: '邻里沟通' },
  { id: 'life-92', english: 'Are you free for a BBQ this weekend?', chinese: '这个周末有空烧烤吗？', scenario: '邻里沟通' },
  { id: 'life-93', english: 'Sorry for the noise last night.', chinese: '抱歉昨晚吵到你了。', scenario: '邻里沟通' },
  { id: 'life-94', english: 'Could you please collect my mail?', chinese: '你可以帮我收一下邮件吗？', scenario: '邻里沟通' },
  { id: 'life-95', english: "I'm having a small get‑together.", chinese: '我办个小聚会。', scenario: '邻里沟通' },
  { id: 'life-96', english: 'Do you know who owns this dog?', chinese: '你知道这只狗是谁的吗？', scenario: '邻里沟通' },
  { id: 'life-97', english: 'The bins will be collected tomorrow.', chinese: '垃圾桶明天收。', scenario: '邻里沟通' },
  { id: 'life-98', english: 'Please keep the gate closed.', chinese: '请关好大门。', scenario: '邻里沟通' },
  { id: 'life-99', english: 'Would you like some vegetables from my garden?', chinese: '你想要一些我菜园的蔬菜吗？', scenario: '邻里沟通' },
  { id: 'life-100', english: "Let's walk together sometime.", chinese: '我们找时间一起散步。', scenario: '邻里沟通' }
];

// 每日英语：今日句子
const dailySentences = [
  { english: 'No worries.', chinese: '没关系。' },
  { english: "She'll be right.", chinese: '她没事的。' },
  { english: "I'm knackered.", chinese: '我累坏了。' },
  { english: 'Catch you later.', chinese: '回头见。' },
  { english: "I’m just having a look, thanks.", chinese: '我只是看看，谢谢。' },
  { english: 'Could I have a takeaway?', chinese: '我可以打包吗？' },
  { english: "It's a bit chilly today.", chinese: '今天有点冷。' },
  { english: "Sorry, I’m running late.", chinese: '抱歉，我要迟到了。' },
  { english: "It's not far from here.", chinese: '离这里不远。' },
  { english: "I'll see what I can do.", chinese: '我会看看能做什么。' },
  { english: 'Just give me a minute.', chinese: '请等我一下。' },
  { english: 'Do you mind if I join you?', chinese: '介意我加入吗？' },
  { english: 'Could you say that again?', chinese: '你能再说一遍吗？' },
  { english: "I don't understand.", chinese: '我不明白。' },
  { english: "That's a good deal.", chinese: '这个很划算。' },
  { english: 'Have a good one!', chinese: '祝你过得愉快！' },
  { english: 'Take care.', chinese: '保重。' },
  { english: "What's the time?", chinese: '现在几点？' },
  { english: "I'm not sure.", chinese: '我不确定。' },
  { english: "It doesn't matter.", chinese: '没关系。' }
];

// 每日英语：短语
const dailyPhrases = [
  { english: 'No worries', chinese: '没关系' },
  { english: 'Fair dinkum', chinese: '真的 / 诚实' },
  { english: 'Bloody oath', chinese: '当然 / 确实' },
  { english: 'Good on ya', chinese: '干得好' },
  { english: "Mate's rates", chinese: '友情价' },
  { english: 'Piece of cake', chinese: '小菜一碟' },
  { english: 'Righto', chinese: '好的' },
  { english: 'Too easy', chinese: '太简单了' },
  { english: 'Good arvo', chinese: '下午好' },
  { english: 'Heaps good', chinese: '非常好' },
  { english: 'No dramas', chinese: '没问题' },
  { english: 'Sweet as', chinese: '很棒' },
  { english: 'Hard yakka', chinese: '辛苦工作' },
  { english: 'Servo', chinese: '加油站' },
  { english: 'Bottle-o', chinese: '酒类商店' },
  { english: 'Brekkie', chinese: '早餐' },
  { english: "Macca's", chinese: '麦当劳' },
  { english: 'Bikkie', chinese: '饼干' },
  { english: 'Brolly', chinese: '雨伞' },
  { english: "G'day", chinese: '你好' }
];

// 每日英语：单词
const dailyWords = [
  { english: 'arvo', chinese: '下午' },
  { english: 'mate', chinese: '朋友' },
  { english: 'loo', chinese: '厕所' },
  { english: 'thongs', chinese: '拖鞋' },
  { english: 'chook', chinese: '鸡' },
  { english: 'barbie', chinese: '烧烤' },
  { english: 'esky', chinese: '冰箱（便携冷藏箱）' },
  { english: 'snag', chinese: '香肠' },
  { english: 'ute', chinese: '皮卡车' },
  { english: 'rego', chinese: '车辆注册' },
  { english: 'jumper', chinese: '毛衣' },
  { english: 'bogan', chinese: '没文化的人' },
  { english: 'ripper', chinese: '极好的事' },
  { english: 'footy', chinese: '澳式足球' },
  { english: 'drongo', chinese: '笨蛋' },
  { english: 'trackie dacks', chinese: '运动裤' },
  { english: 'cuppa', chinese: '一杯茶' },
  { english: 'sunnies', chinese: '太阳镜' },
  { english: 'mozzie', chinese: '蚊子' },
  { english: 'brolly', chinese: '雨伞' }
];

// Australian vocabulary words for the dedicated vocabulary module. Each entry includes an id, English word and Chinese translation.
const vocabData = [
  {
    id: 'v-1',
    english: 'receipt',
    chinese: '收据',
    example1: 'Keep the receipt as proof of purchase.',
    example2: 'Can I have a receipt, please?'
  },
  {
    id: 'v-2',
    english: 'roster',
    chinese: '排班表',
    example1: 'I checked my roster for next week.',
    example2: 'My roster changed at the last minute.'
  },
  {
    id: 'v-3',
    english: 'bulk billing',
    chinese: '医保全报销',
    example1: 'The clinic offers bulk billing for Medicare.',
    example2: 'Is this visit covered by bulk billing?'
  },
  {
    id: 'v-4',
    english: 'rego',
    chinese: '车辆注册',
    example1: "Don't forget to renew your car’s rego.",
    example2: 'You need to pay your rego annually.'
  },
  {
    id: 'v-5',
    english: 'trolley',
    chinese: '购物车',
    example1: 'He pushed the trolley through the grocery store.',
    example2: 'Put your bags in the trolley.'
  },
  {
    id: 'v-6',
    english: 'footpath',
    chinese: '人行道',
    example1: 'Cyclists should not ride on the footpath.',
    example2: 'We walked along the footpath by the beach.'
  },
  {
    id: 'v-7',
    english: 'bin',
    chinese: '垃圾桶',
    example1: 'Please put the rubbish in the bin.',
    example2: 'The bin is collected every Tuesday.'
  },
  {
    id: 'v-8',
    english: 'tyre',
    chinese: '轮胎',
    example1: 'The tyre was flat and needed replacing.',
    example2: 'Check your tyre pressure regularly.'
  },
  {
    id: 'v-9',
    english: 'servo',
    chinese: '加油站',
    example1: 'I stopped at the servo for petrol.',
    example2: 'There’s a servo on the highway.'
  },
  {
    id: 'v-10',
    english: 'bathers',
    chinese: '泳衣',
    example1: 'She bought new bathers for the beach.',
    example2: "Don't forget your bathers for the pool."
  },
  {
    id: 'v-11',
    english: 'op shop',
    chinese: '旧货店',
    example1: 'I found a great jacket at the op shop.',
    example2: 'Op shops sell second-hand goods.'
  },
  {
    id: 'v-12',
    english: 'metho',
    chinese: '甲醇（酒精）',
    example1: 'We used metho to clean the windows.',
    example2: 'Metho can remove stubborn stains.'
  },
  {
    id: 'v-13',
    english: 'snag',
    chinese: '香肠',
    example1: 'He cooked snags on the barbecue.',
    example2: 'I love snags with tomato sauce.'
  },
  {
    id: 'v-14',
    english: 'cuppa',
    chinese: '一杯茶',
    example1: "Let's have a cuppa and chat.",
    example2: 'He enjoys a cuppa in the afternoon.'
  },
  {
    id: 'v-15',
    english: 'arvo',
    chinese: '下午',
    example1: "I'll see you this arvo.",
    example2: "Let's catch up this arvo."
  },
  {
    id: 'v-16',
    english: 'sanga',
    chinese: '三明治',
    example1: 'I made a cheese sanga for lunch.',
    example2: 'He grabbed a sanga on the go.'
  },
  {
    id: 'v-17',
    english: 'tradie',
    chinese: '技工、工人',
    example1: 'The tradie fixed the leaking tap.',
    example2: 'A tradie installed our new sink.'
  },
  {
    id: 'v-18',
    english: 'mozzie',
    chinese: '蚊子',
    example1: 'Put on spray to keep mozzies away.',
    example2: 'Mozzies were buzzing everywhere last night.'
  },
  {
    id: 'v-19',
    english: 'firie',
    chinese: '消防员',
    example1: 'A firie rescued the cat from the tree.',
    example2: 'The firies arrived within minutes.'
  },
  {
    id: 'v-20',
    english: 'ripper',
    chinese: '极好的事',
    example1: 'That was a ripper of a goal!',
    example2: 'We had a ripper time at the party.'
  }
];

// 为了使这些数据可以在其他脚本文件中访问，
// 将它们直接挂载到全局 window 对象（浏览器环境中）。
// 在某些环境下使用 file:// 可能导致 typeof window 判断异常，因此直接赋值。
/* eslint-disable no-undef */
try {
  window.childcareData = childcareData;
  window.nursingData = nursingData;
  window.lifeData = lifeData;
  window.dailySentences = dailySentences;
  window.dailyPhrases = dailyPhrases;
  window.dailyWords = dailyWords;
  window.vocabData = vocabData;
} catch (e) {
  // 如果 window 不存在（如 Node 环境），忽略赋值。
}